# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbcefb56a3691488b551060b84e1bd8f0b5cab9edf2a4db55f20b85a636085d41dfed95d0dd71d447975c4d63224b4e70d6b66d85c80d4500e5548df0b7e9ae5

test:
  secret_key_base: d7d86c0b58f68b723b5aeb76c330420de0b8eb17eeeb1eea17bdbd2ea8787de9d6b46ae74fd1874a12336cb9d71b219fcdcae8b81a3e3500b285c1f60c925d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
